### PR TITLE
Move RC Logger and isAggregatedMergeSplit to ReconfigurationConfig

### PR DESCRIPTION
**Pull request by kanantharamu**
This avoids dependency on `Reconfigurator`

### CODE REVIEW

**Comment by kanantharamu** [comment]
Also noting that the logging class name in configuration files will change after this change.

**Comment by v-arun** [comment]
Can you give me the chain for why isAggregatedMergeSplit needs to be moved?

**Comment by kanantharamu** [comment]
`PaxosConfig.java -> NoopPaxosApp.java -> PaxosAppRequest.java -> RequestPacket.java -> PaxosPacket.java -> AcceptPacket.java -> PaxosMessenger.java -> BatchedCommit.java -> IntegerMap.java -> PaxosManager.java -> ClientRequest.java -> AbstractReplicaCoordinator.java -> Reconfigurable.java -> ReconfigurableRequest.java -> ReconfigurationPacket.java -> RCRecordRequest.java -> AbstractReconfiguratorDB.java`

`AbstractReconfiguratorDB.java` calls `isAggregatedMergeSplit`

**Comment by kanantharamu** [comment]
But I see that it depends on `PaxosManager` in an intermediate step. Ideally this should go away.

**Comment by kanantharamu** [comment]
With respect to the above comment, even if `PaxosManager` goes away, the following remains:

`BasicReconfigurationPacket.java -> ReconfigurationPacket.java -> ReconfigureActiveNodeConfig.java -> AbstractReconfiguratorDB.java`

 `ReconfigurableAppClientAsync.java -> CreateServiceName.java -> BatchedCreateServiceName.java -> BasicReconfigurationPacket.java -> ReconfigurationPacket.java -> RCRecordRequest.java -> AbstractReconfiguratorDB.java`

 `ReconfigurableAppClientAsync.java -> CreateServiceName.java -> BatchedCreateServiceName.java -> BasicReconfigurationPacket.java -> ReconfigurationPacket.java -> StartEpoch.java -> AbstractReconfiguratorDB.java`

 `ReconfigurableAppClientAsync.java -> CreateServiceName.java -> BatchedCreateServiceName.java -> BasicReconfigurationPacket.java -> ReconfigurationPacket.java -> ReconfigureRCNodeConfig.java -> AbstractReconfiguratorDB.java`

**Comment by v-arun** [comment]
Thanks. The cleaner way would be to break the dependency on AbstractReconfiguratorDB (that is the guts of the server side), say, by moving its RecordNames enum to ReconfigurationConfig.

**Pull request merged**
