### PR TITLE
Move RequestAndCallback from PaxosManager to PaxosConfig

### PR DESCRIPTION
**Pull request by kanantharamu**
Move RequestAndCallback from PaxosManager to PaxosConfig to avoid unnecessary dependency on PaxosManager.

### CODE REVIEW

**Comment by v-arun** [comment]
Can you clarify why RequestAndCallback needs to be moved?

**Comment by kanantharamu** [comment]
Dependency in `paxosutil.PendingDigests`

**Comment by v-arun** [comment]
Can you give me the chain all the way from ReconfigurableAppClientAsync? Just for my understanding.

**Comment by kanantharamu** [comment]
An example chain is `PaxosConfig.java -> NoopPaxosApp.java -> RequestPacket.java -> PendingDigests.java`

**Comment by kanantharamu** [comment]
One more is `PaxosConfig.java -> ReplicableRequest.java -> AbstractReplicaCoordinator.java -> RequestPacket.java -> PendingDigests.java`

**Comment by v-arun** [comment]
Thanks. I would have moved the PendingDigest.getMessageDigest() logic as it is more generic. RequestAndCallback is rather specific to PaxosManager.

But I merged it anyway.

**Pull request merged**
